"""Mushaf page viewer with word-level masking and recitation highlighting.

Displays a Mushaf page entirely masked by a solid color. As recitation
progresses, specific word regions are unmasked and overlaid with green/red
to indicate correct/incorrect recitation.

Word bounding boxes and ayah marker positions are loaded from a pre-computed
JSON file generated by scripts/generate_masks.py using OpenCV.
"""

import json
import os
import re
import difflib

from PyQt6.QtWidgets import QGraphicsView, QGraphicsScene
from PyQt6.QtGui import QPixmap, QColor, QPen
from PyQt6.QtCore import Qt, QRectF

from src.config import DATASET_DIR, QURAN_JSON


class MushafView(QGraphicsView):
    """Qt widget that displays a masked Mushaf page with recitation feedback."""

    # Cache for the mask coordinates JSON (loaded once, shared across instances)
    _mask_coords_cache = None

    def __init__(self, parent=None):
        super().__init__(parent)
        self.scene = QGraphicsScene(self)
        self.setScene(self.scene)
        
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setFrameShape(QGraphicsView.Shape.NoFrame)
        self.setStyleSheet("background: transparent;")
        
        self.page_item = None
        self.mask_item = None
        
        # word_boxes maps (surah_id, ayah_id, word_index) to QRectF
        self.word_boxes = {}
        self.highlight_items = {}
        
        # Colors
        self.mask_color = Qt.GlobalColor.white 
        self.correct_color = QColor(0, 255, 0, 80)    # Green, semi-transparent
        self.incorrect_color = QColor(255, 0, 0, 80)  # Red, semi-transparent

        self.current_page_num = None

    def resizeEvent(self, event):
        super().resizeEvent(event)
        if self.scene.sceneRect().isValid():
            self.fitInView(self.scene.sceneRect(), Qt.AspectRatioMode.KeepAspectRatio)

    @classmethod
    def _load_mask_coords(cls) -> dict:
        """Load the pre-computed mask coordinates JSON (cached after first load)."""
        if cls._mask_coords_cache is not None:
            return cls._mask_coords_cache
        
        coords_path = DATASET_DIR / "Quran_pages_mask_coords.json"
        if not coords_path.exists():
            print(f"ERROR: Mask coordinates file not found: {coords_path}")
            print("Please run: python scripts/generate_masks.py")
            return {}
        
        with open(coords_path, "r", encoding="utf-8") as f:
            cls._mask_coords_cache = json.load(f)
        
        print(f"Loaded mask coordinates for {len(cls._mask_coords_cache)} pages.")
        return cls._mask_coords_cache

    def load_page(self, page_num: int):
        """Load and display a Mushaf page with word masks."""
        self.scene.clear()
        self.word_to_box = {}
        self.current_page_num = page_num
        
        # 1. Load Background Image
        img_path = DATASET_DIR / "Quran_pages_white_background" / f"{page_num:03d}.png"
        
        pixmap = QPixmap(str(img_path))
        if pixmap.isNull():
            print(f"Error: Could not load image at {img_path}")
            return
            
        self.page_item = self.scene.addPixmap(pixmap)
        self.scene.setSceneRect(QRectF(pixmap.rect()))
        self.fitInView(self.scene.sceneRect(), Qt.AspectRatioMode.KeepAspectRatio)
        
        # 2. Load pre-computed bounding boxes from JSON
        mask_coords = self._load_mask_coords()
        page_data = mask_coords.get(str(page_num))
        if page_data is None:
            print(f"Warning: No mask coordinates for page {page_num}")
            return
        
        # Build flat_boxes from the pre-computed word_boxes
        flat_boxes = {}
        for wb in page_data["word_boxes"]:
            idx = wb["flat_idx"]
            rect = QRectF(wb["x"], wb["y"], wb["w"], wb["h"])
            flat_boxes[idx] = rect

        # 3. Extract flat tokens for alignment with quran.json
        flat_tokens = []
        txt_path = DATASET_DIR / "Quran_pages_lines_ayah_marker.txt"
        try:
            page_lines = []
            in_page = False
            with open(txt_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("📄 Page"):
                        if int(line.split()[2]) == page_num:
                            in_page = True
                        elif in_page:
                            break
                    elif in_page and line.startswith("Line"):
                        parts = line.split(":", 1)
                        if len(parts) == 2:
                            page_lines.append(parts[1].strip())
        except Exception as e:
            print(f"Error reading lines txt: {e}")
            return
            
        for line_text in page_lines:
            line_text = line_text.replace(" | ", " ").replace("|", " ")
            
            # Skip Surah headers
            if line_text.startswith("سورة") and len(line_text.split()) <= 3:
                continue
                
            # Skip standalone Bismillah lines
            if line_text.strip() == "﷽":
                continue
                
            # Handle special case (Page 187: Surah At-Tawbah) where Bismillah 
            # is incorrectly placed on the same line as the Ayah text in the dataset
            if "﷽" in line_text:
                line_text = line_text.replace("﷽", "").strip()
                
            tokens = line_text.split()
            for t in tokens:
                # Skip ayah marker tokens — they are handled by CV marker detection
                if re.match(r'^﴿.*?﴾$', t):
                    continue
                flat_tokens.append(t)
                
        # 4. Align with quran.json
        def _normalize_for_alignment(t):
            t = t.replace('ـ', '')
            t = re.sub(r'[أإآٱ]', 'ا', t)
            t = t.replace('ى', 'ي')
            t = t.replace('ؤ', 'و')
            t = t.replace('ئ', 'ي')
            t = t.replace('ة', 'ه')
            t = re.sub(r'[ً-ٰٟۖ-ۜ۟-۪ۨ-ۭ]', '', t)
            t = re.sub(r'[^\w\s]', '', t)
            t = re.sub(r'\d+', '', t)
            t = re.sub(r'[٠-٩]', '', t)
            t = t.replace('ا', '')
            return t.strip()
            
        data_json_path = DATASET_DIR / "Quran_pages_data_json" / f"page_{page_num}.json"
        try:
            with open(QURAN_JSON, 'r', encoding='utf-8') as f:
                quran_data = json.load(f)
            with open(data_json_path, 'r', encoding='utf-8') as f:
                page_ayahs = json.load(f).get("ayahs", [])
                
            q_words_flat = []
            q_words_meta = []
            for ayah_meta in page_ayahs:
                s = ayah_meta["sura"]
                a = ayah_meta["ayah"]
                for sura_node in quran_data:
                    if sura_node["id"] == s:
                        for verse in sura_node["verses"]:
                            if verse["id"] == a:
                                for idx, qw in enumerate(verse["text"].split()):
                                    q_words_flat.append(qw)
                                    q_words_meta.append((s, a, idx))
                                break
                        break
                        
            q_norm = [_normalize_for_alignment(w) for w in q_words_flat]
            f_norm = [_normalize_for_alignment(w) for w in flat_tokens]
            
            for meta in q_words_meta:
                self.word_to_box[meta] = []
                
            sm = difflib.SequenceMatcher(None, q_norm, f_norm)
            for op, i1, i2, j1, j2 in sm.get_opcodes():
                if op == 'equal' or op == 'replace':
                    for k in range(max(i2 - i1, j2 - j1)):
                        qi = i1 + k if i1 + k < i2 else i2 - 1
                        fi = j1 + k if j1 + k < j2 else j2 - 1
                        meta = q_words_meta[qi]
                        if fi not in self.word_to_box[meta]:
                            self.word_to_box[meta].append(fi)
                elif op == 'insert':
                    for fi in range(j1, j2):
                        if i1 > 0:
                            meta = q_words_meta[i1 - 1]
                            self.word_to_box[meta].append(fi)
                        elif i1 < len(q_words_meta):
                            meta = q_words_meta[i1]
                            self.word_to_box[meta].append(fi)
        except Exception as e:
            print(f"Error mapping words: {e}")

        # 5. Create QGraphicsRectItems for each word box (opaque white mask)
        self.box_items = {}
        for idx, rect in flat_boxes.items():
            item = self.scene.addRect(rect)
            item.setPen(QPen(Qt.GlobalColor.transparent))
            item.setBrush(QColor(255, 255, 255, 255))  # Opaque white mask
            self.box_items[idx] = item

    def update_recitation(self, surah: int, ayah: int, word_index: int, is_correct: bool):
        """Unmask and highlight a word based on recitation correctness."""
        if not hasattr(self, 'box_items'):
            return
            
        box_indices = self.word_to_box.get((surah, ayah, word_index))
        if box_indices is None:
            return
            
        for b_idx in box_indices:
            item = self.box_items.get(b_idx)
            if item:
                if is_correct:
                    item.setBrush(QColor(34, 197, 94, 80)) # Green
                else:
                    item.setBrush(QColor(239, 68, 68, 80)) # Red
